### ISSUE TITLE
文件下载支持filename*=

### ISSUE THREAD

**Issue by nilIfNull** [ballcat-projects/ballcat-admin-ui-vue3#28]
我遇到了文件名乱码的情况：
filename*=格式：
`attachment;filename*=utf-8''%E7%94%A8%E6%88%B7%E5%AF%BC%E5%85%A5%E6%A8%A1%E7%89%88.xlsx`

参考[jshttp/content-disposition](https://github.com/jshttp/content-disposition) 做了修改解决了问题，但是感觉写得不够好就没提交PR。

大佬是否有更优雅解决方案？

**Comment by Hccake** [comment]
参看国际化页面 => 导入 => 下载模板文件，该模板文件名为中文，可正常下载。
