### ISSUE TITLE
DictSelect组件无下拉选项

### ISSUE THREAD

**Issue by nilIfNull** [ballcat-projects/ballcat-admin-ui-vue3#30]
最近更新的内容影响到了自定义组件DictSelect，如图
![image](https://github.com/ballcat-projects/ballcat-admin-ui-vue3/assets/3170158/a98d3f6e-ba1a-48a3-99be-2d4fec1c343b)

**Comment by Hccake** [comment]
纯 TS 方案封装 ant design vue 的 Select 组件，在升级 vue3.3.x 后出现异常，需要 ant-design-vue 做对应代码调整，暂时切换使用 Vue Prop Type 方式完成对应功能
