### ISSUE TITLE
配置国际化关闭后出现bug

### ISSUE THREAD

**Issue by evil0th** [ballcat-projects/ballcat-admin-ui-vue3#35]
config设置`enableI18n=false`时，以下(但不限于)功能会有问题：

- antd组件显示为英文，如分页
- dayjs locale未初始化
- axios请求util中国际化message显示为message.key

**Comment by Hccake** [comment]
这两天没空处理，你可以先试下 2.x 分支有没有这个问题。没问题的话迟两天我 cherry pick 过来

**Comment by evil0th** [comment]
2.0.0分支同样问题
<img width="200" alt="image" src="https://github.com/ballcat-projects/ballcat-admin-ui-vue3/assets/3170158/a5c6662f-b48e-4d72-b6eb-66533c0f8f28">

**Comment by Hccake** [comment]
好，等两天修复

**Comment by Hccake** [comment]
已修复和推送，你可以测试下，如果有问题在这里继续反馈

**Comment by evil0th** [comment]
测试确认已修复，感谢！
