### ISSUE TITLE
请问作者，protable还有没有处理返回值的钩子函数，类似于v2版本的responseDataProcess方法

### ISSUE THREAD

**Issue by coderbinbin** [ballcat-projects/ballcat-admin-ui-vue3#42]
请问作者，protable还有没有处理返回值的钩子函数，类似于v2版本的responseDataProcess方法

**Comment by Hccake** [comment]
v3 版本不需要这个钩子函数了，proTable 的 tableRequest 属性是一个函数，你可以自己控制该函数的内部实现细节，决定返回数据值。

可以参考 src/views/system/organization/SysOrganizationPage.vue 页面的 tableRequest 值
